ALTER TYPE "Category" ADD VALUE IF NOT EXISTS 'BANKING';
ALTER TYPE "Category" ADD VALUE IF NOT EXISTS 'BILL_OR_UTILITY';
ALTER TYPE "Category" ADD VALUE IF NOT EXISTS 'TRAVEL';
ALTER TYPE "Category" ADD VALUE IF NOT EXISTS 'JOB_OR_CAREER';
ALTER TYPE "Category" ADD VALUE IF NOT EXISTS 'HEALTHCARE';
ALTER TYPE "Category" ADD VALUE IF NOT EXISTS 'GOVERNMENT';
ALTER TYPE "Category" ADD VALUE IF NOT EXISTS 'EDUCATION';
