ALTER TYPE "Category" ADD VALUE IF NOT EXISTS 'SOCIAL_OR_COMMUNITY';
ALTER TYPE "Category" ADD VALUE IF NOT EXISTS 'PRODUCT_OR_NEWSLETTER';
ALTER TYPE "Category" ADD VALUE IF NOT EXISTS 'SMS_OR_TEXT';
